### PR TITLE
lots of new things

### PR DESCRIPTION
**Pull request by AdamDeJames**
bugs fixed
retardness fixed
new features
can right click on scoreboard to get info about a player, also allowing copy/paste via clicking ie the steamid.
Moderator tools via scoreboard soon.

### CODE REVIEW

**Comment by goigle** [comment]
Did you seriously leave your community's name in the credits?

**Comment by Avgardyan** [comment]
The code is directly ported off CityRP. Nice try, Adam. ;)

**Comment by Pawsative** [comment]
Most of this code looks similar to Fearless's CityRP, such as the scoreboard. Also, any reason for this?:
+	if(self.Player:SteamID()== "STEAM_0:0:48573869") then
  		self.texRating = Material("icon16/shield.png")

And last thing, there was no reason for you to edit the sv_config.lua.

**Comment by Pawsative** [comment]
Oh, and looking at some of the code you removed, CityRPScoreBoard:SetVisible(false) was there, so yeah it's ported off CityRP.

**Pull request closed without merging**
